services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: enterviu-api:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - cv_data:/temp_cvs
    environment:
      - ENV=development
      - RUN_TESTS=false  
      - TZ=Asia/Ho_Chi_Minh
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=host.docker.internal
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DOCKER_ENVIRONMENT=True
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME:-enterviu-ai}
      - MINIO_SECURE=${MINIO_SECURE:-False}
      # QdrantDB Configuration
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_PATH=/app/qdrant_storage
      # AI APIs
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # PayOS Configuration
      - PAYOS_CLIENT_ID=${PAYOS_CLIENT_ID}
      - PAYOS_API_KEY=${PAYOS_API_KEY}
      - PAYOS_CHECKSUM_KEY=${PAYOS_CHECKSUM_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env
    # Add extra_hosts to ensure host.docker.internal works on all Docker environments
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - enterviu-network
    depends_on:
      - minio
      - qdrant

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    networks:
      - enterviu-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
    networks:
      - enterviu-network
    restart: always
  redis-enterviu:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - enterviu-network
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer-enterviu
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=host.docker.internal:${DB_PORT}
      - ADMINER_DESIGN=galkaev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - enterviu-network
    restart: always
    depends_on:
      - api

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.frontend
  #   image: enterviu-frontend:latest
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - API_URL=http://localhost:8000/api
  #   networks:
  #     - enterviu-network
  #   depends_on:
  #     - api

networks:
  enterviu-network:
    driver: bridge

volumes:
  minio-data:
  cv_data:  # Add new volume for CV files
  qdrant-data:  # Add volume for QdrantDB storage

