"""update cvgen

Revision ID: 30309a13186b
Revises: c3e76c20f3a6
Create Date: 2025-07-03 14:35:34.566719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30309a13186b'
down_revision: Union[str, None] = 'c3e76c20f3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_generation',
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('cv_extraction_id', sa.String(length=255), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('color_theme', sa.String(length=50), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('latex_source', sa.Text(), nullable=True),
    sa.Column('pdf_file_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('generation_time', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('llm_model_used', sa.String(length=100), nullable=True),
    sa.Column('llm_input_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_output_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_total_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_cost_usd', sa.Float(), nullable=True),
    sa.Column('generation_config', sa.JSON(), nullable=True),
    sa.Column('cv_data_snapshot', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_generation_job_id'), 'cv_generation', ['job_id'], unique=True)
    op.create_index(op.f('ix_cv_generation_user_id'), 'cv_generation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_generation_user_id'), table_name='cv_generation')
    op.drop_index(op.f('ix_cv_generation_job_id'), table_name='cv_generation')
    op.drop_table('cv_generation')
    # ### end Alembic commands ###
