"""update group's tables

Revision ID: 8d67d7065ba0
Revises: 23f7711be05b
Create Date: 2025-06-22 14:39:27.834705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8d67d7065ba0'
down_revision: Union[str, None] = '23f7711be05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_members', 'role',
               existing_type=mysql.INTEGER(),
               type_=sa.Enum('LEADER', 'MEMBER', name='groupmemberroleenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_members', 'role',
               existing_type=sa.Enum('LEADER', 'MEMBER', name='groupmemberroleenum'),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
