"""update group and group_member models

Revision ID: c68cff4c4bd5
Revises: 5e0b755fef26
Create Date: 2025-06-16 18:44:07.454788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68cff4c4bd5'
down_revision: Union[str, None] = '5e0b755fef26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_sessions',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_iteration', sa.Integer(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('user_profile_data', sa.JSON(), nullable=True),
    sa.Column('existing_user_data', sa.JSON(), nullable=True),
    sa.Column('generated_questions', sa.JSON(), nullable=True),
    sa.Column('all_previous_questions', sa.JSON(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('missing_areas', sa.JSON(), nullable=True),
    sa.Column('focus_areas', sa.JSON(), nullable=True),
    sa.Column('should_continue', sa.Boolean(), nullable=False),
    sa.Column('workflow_complete', sa.Boolean(), nullable=False),
    sa.Column('total_questions_generated', sa.Integer(), nullable=False),
    sa.Column('analysis_decision', sa.JSON(), nullable=True),
    sa.Column('generation_history', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_sessions_session_id'), 'question_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_question_sessions_user_id'), 'question_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_sessions_user_id'), table_name='question_sessions')
    op.drop_index(op.f('ix_question_sessions_session_id'), table_name='question_sessions')
    op.drop_table('question_sessions')
    # ### end Alembic commands ###
