"""init

Revision ID: cf6752638ff4
Revises: 
Create Date: 2025-04-10 23:54:26.160948

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cf6752638ff4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('public_key', sa.String(length=1000), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('sso_provider', sa.Enum('google', 'github', 'none', name='sso_provider_enum'), nullable=True),
    sa.Column('sso_id', sa.String(length=255), nullable=True),
    sa.Column('device_address', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'MANAGER', 'GUEST', name='userroleenum'), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('role')
    op.drop_table('otp')
    # ### end Alembic commands ###
