"""update

Revision ID: fba69beeee19
Revises: 
Create Date: 2025-07-28 23:33:46.582793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba69beeee19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_kb',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('indexed', sa.Boolean(), nullable=True),
    sa.Column('index_status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranks',
    sa.Column('name', sa.Enum('BASIC', 'PRO', 'ULTRA', name='rankenum'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('benefits', sa.JSON(), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranks_name'), 'ranks', ['name'], unique=True)
    op.create_table('users',
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'MANAGER', 'GUEST', name='userroleenum'), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rank', sa.Enum('BASIC', 'PRO', 'ULTRA', name='rankenum'), nullable=False),
    sa.Column('rank_activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rank_expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agents',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('model_provider', sa.Enum('GOOGLE', name='modelprovider'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('default_system_prompt', sa.Text(), nullable=True),
    sa.Column('tools_config', sa.JSON(), nullable=True),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('api_provider', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('order_code', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_link_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='paymentstatus'), nullable=True),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('transaction_date_time', sa.DateTime(), nullable=True),
    sa.Column('counter_account_bank_id', sa.String(length=255), nullable=True),
    sa.Column('counter_account_bank_name', sa.String(length=255), nullable=True),
    sa.Column('counter_account_name', sa.String(length=255), nullable=True),
    sa.Column('counter_account_number', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_code'), 'payments', ['order_code'], unique=False)
    op.create_index(op.f('ix_payments_payment_link_id'), 'payments', ['payment_link_id'], unique=False)
    op.create_table('subscription_orders',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('order_code', sa.String(length=50), nullable=False),
    sa.Column('rank_type', sa.Enum('BASIC', 'PRO', 'ULTRA', name='rankenum'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELED', 'EXPIRED', name='orderstatusenum'), nullable=False),
    sa.Column('payment_link_id', sa.String(length=100), nullable=True),
    sa.Column('checkout_url', sa.String(length=500), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expired_subscription_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_orders_order_code'), 'subscription_orders', ['order_code'], unique=True)
    op.create_index(op.f('ix_subscription_orders_user_id'), 'subscription_orders', ['user_id'], unique=False)
    op.create_table('user_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('minio_bucket', sa.String(length=255), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('indexing_error', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_sessions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('parent_session_id', sa.String(length=36), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('questions_data', sa.JSON(), nullable=True),
    sa.Column('session_status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['parent_session_id'], ['question_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_files',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_answers',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=255), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('answer_data', sa.JSON(), nullable=False),
    sa.Column('answer_type', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['question_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_answers')
    op.drop_table('message_files')
    op.drop_table('question_sessions')
    op.drop_table('messages')
    op.drop_table('files')
    op.drop_table('user_logs')
    op.drop_index(op.f('ix_subscription_orders_user_id'), table_name='subscription_orders')
    op.drop_index(op.f('ix_subscription_orders_order_code'), table_name='subscription_orders')
    op.drop_table('subscription_orders')
    op.drop_index(op.f('ix_payments_payment_link_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_code'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('conversations')
    op.drop_table('agents')
    op.drop_table('users')
    op.drop_index(op.f('ix_ranks_name'), table_name='ranks')
    op.drop_table('ranks')
    op.drop_table('global_kb')
    # ### end Alembic commands ###
